name: kardesler_kuyumculuk
description: "Kardeşler Kuyumculuk Canlı Altın Takip Uygulaması"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # --- GEREKLİ PAKETLER ---
  http: ^1.1.0
  html: ^0.15.4
  intl: ^0.18.1
  url_launcher: ^6.2.1
  google_fonts: ^6.1.0
  webview_flutter: ^4.7.0  # <-- BU ÇOK ÖNEMLİ, YENİ EKLEDİK!

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dukkan.jpg
    - assets/splash.jpg