name: kardesler_kuyumculuk
description: "Kardeşler Kuyumculuk Canlı Altın Takip Uygulaması"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # --- GEREKLİ PAKETLER ---
  http: ^1.1.0
  html: ^0.15.4
  intl: ^0.18.1
  url_launcher: ^6.2.1
  google_fonts: ^6.1.0
  webview_flutter: ^4.7.0
  firebase_core: ^4.4.0
  firebase_database: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # İkon oluşturucu paket buraya eklendi
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
  # image_scale: 1.0  <-- Bu satırı siliyoruz
  remove_alpha_ios: true
  # Android için ikonun beyaz daire içinde kalmasını engeller:
  adaptive_icon_foreground: "assets/icon.jpg" 
  adaptive_icon_background: "#1A1A1A"

flutter:
  uses-material-design: true
  assets:
    - assets/dukkan.jpg
    - assets/splash.jpg
    # İkon dosyasını da assets altına eklemeyi unutma
    - assets/icon.jpg